enum RANKS_ENLISTED {
  PRIVATE
  COPORAL
  SERGEANT
  STAFF_SERGEANT
  MASTER_SERGEANT
}

enum RANK_OFFICERS {
  LIEUTENANT
  CAPTAIN
  MAJOR
  COLONEL
  GENERAL
}

enum RANK_DIVISIONAL {
  COFOUNDER
  FOUNDER
  CODIVISION_LEADER
  DIVISION_LEADER
}

enum RANK_SENIOR_LEADERSHIP {
  DIRECTOR
  SENIOR_DIRECTOR
  DEPARTMENT_STAFF
}

enum RANKS_BOARD_OF_DIRECTORS {
  CHIEF_EXECUTIVE_OFFICER
  CHIEF_OPERATIONS_OFFICER
  CHIEF_OF_STAFF
  CHIEF_GENERAL_ASSISTANCE
  CHIEF_TECHNICAL_OFFICER
  CHIEF_ADMINISTRATIVE_OFFICER
  CHIEF_WEB_OFFICER
  CHIEF_PERFORMANCE_OFFICER
  CHIEF_PUBLIC_RELATIONS_OFFICER
  CHIEF_MARKETING_OFFICER
}

enum RANKS_CREATORS {
  COCREATOR
  CREATOR
}
enum ENLISTED_ABBR {
  PVT
  CPL
  SGT
  SSGT
  MSGT
}

enum OFFICER_ABBR {
  LT
  CPT
  MAJ
  COL
  GEN
}

enum DIVISIONAL_ABBR {
  COFO
  FDR
  CDL
  DL
}

enum SENIOR_LEADERSHIP_ABBR {
  DIR
  SNRDIR
  DPTSTF
}

enum BOARD_OF_DIRECTORS_ABBR {
  CEO
  COO
  COS
  CGA
  CTO
  CAO
  CWO
  CPO
  CPRO
  CMO
}

enum CREATORS_ABBR {
  CCTR
  CTR
}

union Ranks =
    RANKS_ENLISTED
  | RANK_OFFICERS
  | RANK_DIVISIONAL
  | RANK_SENIOR_LEADERSHIP
  | RANKS_BOARD_OF_DIRECTORS
  | RANKS_CREATORS

union RanksAbbreviations =
    ENLISTED_ABBR
  | OFFICER_ABBR
  | DIVISIONAL_ABBR
  | SENIOR_LEADERSHIP_ABBR
  | BOARD_OF_DIRECTORS_ABBR
  | CREATORS_ABBR
